{
    "api_set": [
        {
            "enabled": false, 
            "name": "Revit", 
            "path": "Autodesk.Revit"
        }, 
        {
            "enabled": true, 
            "name": "System .Net", 
            "path": "System"
        }, 
        {
            "enabled": true, 
            "name": "Microsoft", 
            "path": "Microsoft"
        }, 
        {
            "enabled": true, 
            "name": "IronPython", 
            "path": "IronPython"
        }, 
        {
            "enabled": true, 
            "name": "__main__", 
            "path": "__main__"
        }, 
        {
            "enabled": false, 
            "name": " Modules sys", 
            "path": "sys.modules"
        }, 
        {
            "enabled": false, 
            "name": "CLR", 
            "path": "clr.References"
        }
    ], 
    "window": {
        "Height": 671.0, 
        "Left": 286.0, 
        "Top": 216.0, 
        "Width": 1080.0
    }
}